parameters:
  hot.profiling_bundle.routes.whitelist: []
  hot.profiling_bundle.commands.whitelist: []
  hot.profiling_bundle.spans.whitelist: null
  hot.profiling_bundle.spans.blacklist: null

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $routesWhitelist: '%hot.profiling_bundle.routes.whitelist%'
      $commandsWhitelist: '%hot.profiling_bundle.commands.whitelist%'
      $spansWhitelist: '%hot.profiling_bundle.spans.whitelist%'
      $spansBlacklist: '%hot.profiling_bundle.spans.blacklist%'

  Hot\ProfilingBundle\:
    resource: '../../'
    exclude:
      - '../../ProfilingBundle.php'
